---
title: "Base de dados"
format:
  html:
    theme: yeti
---

```r
library(bigrquery)
library(tidyverse)

conexao_ideb <- dbConnect(
  bigrquery::bigquery(),
  project = "basedosdados",
  dataset = "br_inep_ideb",
  billing = "base-dos-dados-334420"
)

escolas <- tbl(conexao_ideb, "escola")

escolas_df <- escolas |> 
  dplyr::select(tidyselect::everything()) |> 
  collect()
  
  escolas_df |> 
  readr::write_rds("dados/br_inep_ideb_escola.Rds")
```


```{r}
library(tidyverse)
escolas_df <- readr::read_rds("dados/br_inep_ideb_escola.Rds")
```


```{r}
escolas_em <- escolas_df |> 
  dplyr::filter(ensino == "medio") |>
  tidyr::drop_na(ideb)
  

ideb <- escolas_df |> 
  dplyr::filter(rede != "privada") |> 
  dplyr::group_by(ano, ensino, rede) |> 
  dplyr::summarise(media_ideb = mean(ideb, na.rm = TRUE)) |> 
  dplyr::arrange(ano, desc(media_ideb))

ideb |> 
  ggplot() +
  geom_col(aes(x = ano, y = media_ideb)) +
  facet_grid(rede ~ ensino)
```

Qual é a escola de ensino médio com a maior e a menor taxa de aprovação no seu estado no ano mais recente com dados disponíveis?

```{r}
ex1 <-  escolas_df |> 
  tidyr::drop_na(taxa_aprovacao) |> 
  dplyr::filter(sigla_uf == "SP", ano == max(ano), ensino == "medio") 

ex1 |> dplyr::arrange(taxa_aprovacao)
```

```{r}
escolas_df |> 
  dplyr::count(sigla_uf, ano, ensino, rede)
```

