---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# cebrap.lab online -  Introdução ao R

## Informações gerais

- **Ministrante:** [Beatriz Milz](https://beatrizmilz.com/about/)

- **Data/horário:** 9 a 13 de maio/2022;  
  - Segunda, Quarta e Sexta: aula ao vivo, online, das 18h30 às 21h30. 
  - Terça e quinta: haverão tarefas para casa, para praticar os conceitos.

- **Inscrições:** <https://cursos.cebrap.org.br/cursos/introducao-ao-r/>

- **Sobre o curso:** A linguagem de programação R é utilizada para organização, análise e apresentação de dados.  O curso apresentará a linguagem R e o ambiente de desenvolvimento (IDE) RStudio. Serão apresentados conceitos usando R base, e então falaremos em como fazer algumas tarefas usando o pacote tidyverse, como: importar uma tabela para o R, exportar uma tabela para o computador, selecionar colunas, filtrar linhas, ordenar uma base de dados, transformar variáveis, obter sumarização por grupos, obter estatísticas descritivas, gerar gráficos simples, entre outros. O curso tem como público alvo pessoas que tenham interesse em utilizar R para análise de dados. Todas as ferramentas utilizadas são gratuitas.


## Materiais

### Slides

- [Slide de apresentação do curso](https://beatrizmilz.github.io/cebrap-lab-intro-R-5-2022/slides/introducao-ao-curso.html#/)

- [Slide de correção do exercício 1](https://beatrizmilz.github.io/cebrap-lab-intro-R-5-2022/slides/aula-2.html)

### Scripts

Abaixo estão os scripts usados no RStudio Cloud após a aula:

- [R Base](https://github.com/beatrizmilz/cebrap-lab-intro-R-5-2022/tree/main/materiais_rstudio_cloud_pos_aula/Topico-1-R-base)

- [Importação](https://github.com/beatrizmilz/cebrap-lab-intro-R-5-2022/tree/main/materiais_rstudio_cloud_pos_aula/Topico-2-importacao)


- [Baixar zip completo](https://github.com/beatrizmilz/cebrap-lab-intro-R-5-2022/archive/refs/heads/main.zip) - é melhor baixar após o curso!


### Links citados em aula

Em breve!


## Outras informações

Material do curso de 2019 (ministrado por Leonardo Barone): <https://github.com/leobarone/cebrap_lab_programacao_r>



